#!/usr/bin/env node
/*
 * Generates assets/js/config.js from .env.local (or process.env).
 * config.js is gitignored — it is the ONLY place the Apps Script URL is
 * written to disk on the client side, and it is regenerated per-deploy,
 * never hand-edited or committed.
 *
 * Only NEXT_PUBLIC_-prefixed vars are read here — GOOGLE_SCRIPT_URL is
 * treated as server-only and intentionally never touches this file.
 *
 * Usage: node scripts/generate-config.js
 * Run this once locally (or in your deploy step) before serving the site.
 */
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.join(__dirname, '..');
var ENV_FILE = path.join(ROOT, '.env.local');
var OUT_FILE = path.join(ROOT, 'assets', 'js', 'config.js');

function loadEnvLocal(filePath) {
  var env = {};
  if (!fs.existsSync(filePath)) return env;
  var lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);
  lines.forEach(function (line) {
    var trimmed = line.trim();
    if (!trimmed || trimmed.indexOf('#') === 0) return;
    var idx = trimmed.indexOf('=');
    if (idx === -1) return;
    var key = trimmed.slice(0, idx).trim();
    var value = trimmed.slice(idx + 1).trim();
    env[key] = value;
  });
  return env;
}

var fileEnv = loadEnvLocal(ENV_FILE);

function readVar(name) {
  return process.env[name] || fileEnv[name] || '';
}

var scriptUrl = readVar('NEXT_PUBLIC_SCRIPT_URL');
var n8nCtaWebhookUrl = readVar('NEXT_PUBLIC_N8N_CTA_WEBHOOK_URL');

if (!scriptUrl) {
  console.error('generate-config: NEXT_PUBLIC_SCRIPT_URL not found in .env.local or the environment. Aborting.');
  process.exit(1);
}

var contents = '/* AUTO-GENERATED by scripts/generate-config.js — do not edit by hand, do not commit. */\n' +
  'window.WANGOES_CONFIG = {\n' +
  '  SCRIPT_URL: ' + JSON.stringify(scriptUrl) + ',\n' +
  '  N8N_CTA_WEBHOOK_URL: ' + JSON.stringify(n8nCtaWebhookUrl) + '\n' +
  '};\n';

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, contents, 'utf8');
console.log('generate-config: wrote ' + path.relative(ROOT, OUT_FILE));
